version: '3.8'

services:
    app:
        container_name: laravel_app
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - .:/var/www/html
            - ./test.php:/index.php
        networks:
            - laravel_network

    web:
        container_name: nginx
        image: nginx:alpine
        volumes:
            - ./nginx/default.conf:/etc/nginx/nginx.conf
            - .:/var/www/html
        ports:
            - "80:80"
        depends_on:
            - app
        networks:
            - laravel_network

    db:
        container_name: postgres_db
        image: postgres:latest
        environment:
            POSTGRES_USER: laravel
            POSTGRES_PASSWORD: secret
            POSTGRES_DB: laravel_db
        volumes:
            - db_data:/var/lib/postgresql/data
        networks:
            - laravel_network

networks:
    laravel_network:
        driver: bridge

volumes:
    db_data:
